import numpy as np
import matplotlib.pyplot as plt
expid='REF004'
i,rg,rl,rn,h,le,leg,lev,letr,g,ts,t2,wg,w2,t2m,wsoil1=np.loadtxt('../data_out/surface_fluxes_and_variables_exp_'+expid+'.dat',unpack=True)
fig=plt.figure()
ax1=fig.add_subplot(311)
ax1.plot(i,rn,label='Rn',linewidth=2)
ax1.plot(i,h,label='H',linewidth=2)
ax1.plot(i,le,label='LE',linewidth=2)
ax1.plot(i,letr,label='LETR',linewidth=2)
ax1.plot(i,g,label='G',linewidth=2)
#ax1.plot(i,rn-h-le,label='Rn-H-LE',linewidth=2)
#ax1.set_ylim(0.,2000.)
ax1.legend(loc='best',fontsize='small')
ax1.set_xlabel('Time steps')
ax1.set_ylabel('Watts/m2')
ax2=fig.add_subplot(312)
ax2.plot(i,t2m-273.15,label='T2m',linewidth=2)
ax2.plot(i,ts-273.15,label='Ts',linewidth=2)
ax2.plot(i,t2-273.15,label='T2',linewidth=2)
#ax2.set_ylim(0.,2000.)
ax2.legend(loc='best',fontsize='small')
ax2.set_xlabel('Time steps')
ax2.set_ylabel('K')
ax3=fig.add_subplot(313)
#ax3.plot(i,wg,label='wg',linewidth=2)
#ax3.plot(i,w2,label='w2',linewidth=2)
#ax3.set_ylim(0.,2000.)
ax3.plot(i,wsoil1,label='wsoil1',linewidth=2)
ax3.plot(i,wg,label='wg',linewidth=2)
ax3.legend(loc='best',fontsize='small')
ax3.set_xlabel('Time steps')
ax3.set_ylabel('m3/m3')
figure = plt.gcf()
figure.set_size_inches(7, 11)
plt.savefig('../plots/Figure2_'+expid,dpi=600)
plt.show()

