import numpy as np
import matplotlib.pyplot as plt
expid='REF028'
za,tha,qva,ua,va,km,kh=np.loadtxt('../data_out/atmospheric_profiles_exp_'+expid+'.dat',unpack=True)
dt=900.0
nlev=80
nstep=int(48*3600/dt) + 1
xvar=np.reshape(qva,(nstep,nlev))
var1=xvar.transpose()
x1 = np.arange(0,nstep)
y1 = np.arange(0,nlev)
X1, Y1 = np.meshgrid(x1,y1)

plt.xlabel('Hour')
plt.ylabel('Level number')
plt.ylim(nlev-1,1,-1)
plt.xlim(0,nstep-1)
plt.xticks(np.arange(0,nstep,12))
plt.yticks(np.arange(0,nlev-1,5))
xvar=np.reshape(qva,(nstep,nlev))
var1=xvar.transpose()
plt.title('Specific humidity (g/kg)')
figure = plt.gcf()
figure.set_size_inches(7, 4)
plt.contourf(X1,Y1,var1*1E3,20,cmap='OrRd')
plt.colorbar()
plt.contour(X1,Y1,var1*1E3,20,colors='black',linewidths=0.5)
plt.savefig('../plots/specific_humidity_'+expid+'.png',dpi=600)
plt.show()

plt.xlabel('Hour')
plt.ylabel('Level number')
plt.ylim(nlev-1,1,-1)
plt.xlim(0,nstep-1)
plt.xticks(np.arange(0,nstep,12))
plt.yticks(np.arange(0,nlev-1,5))
xvar=np.reshape(tha,(nstep,nlev))
var1=xvar.transpose()
plt.title('Potential temperature (°C)')
figure = plt.gcf()
figure.set_size_inches(7, 4)
plt.contourf(X1,Y1,var1-273.15,20,cmap='jet')
plt.colorbar()
plt.contour(X1,Y1,var1-273.15,20,colors='black',linewidths=0.5)
plt.savefig('../plots/potential_temperature_'+expid+'.png',dpi=600)
plt.show()

plt.xlabel('Hour')
plt.ylabel('Level number')
plt.ylim(nlev-1,1,-1)
plt.xlim(0,nstep-1)
plt.xticks(np.arange(0,nstep,12))
plt.yticks(np.arange(0,nlev-1,5))
xvar=np.reshape(ua,(nstep,nlev))
var1=xvar.transpose()
plt.title('Zonal wind (m/s)')
figure = plt.gcf()
figure.set_size_inches(7, 4)
plt.contourf(X1,Y1,var1,20,cmap='jet')
plt.colorbar()
plt.contour(X1,Y1,var1,20,colors='black',linewidths=0.5)
plt.savefig('../plots/zonal_wind_'+expid+'.png',dpi=600)
plt.show()

plt.xlabel('Hour')
plt.ylabel('Level number')
plt.ylim(nlev-1,1,-1)
plt.xlim(0,nstep-1)
plt.xticks(np.arange(0,nstep,12))
plt.yticks(np.arange(0,nlev-1,5))
xvar=np.reshape(va,(nstep,nlev))
var1=xvar.transpose()
plt.title('Meridional wind (m/s)')
figure = plt.gcf()
figure.set_size_inches(7, 4)
plt.contourf(X1,Y1,var1,20,cmap='jet')
plt.colorbar()
plt.contour(X1,Y1,var1,20,colors='black',linewidths=0.5)
plt.savefig('../plots/meridional_wind_'+expid+'.png',dpi=600)
plt.show()

plt.xlabel('Hour')
plt.ylabel('Level number')
plt.ylim(nlev-1,1,-1)
plt.xlim(0,nstep-1)
plt.xticks(np.arange(0,nstep,12))
plt.yticks(np.arange(0,nlev-1,5))
xvar=np.reshape(kh,(nstep,nlev))
var1=xvar.transpose()
plt.title('Heat exchange coefficient (m$^2$/s)')
figure = plt.gcf()
figure.set_size_inches(7, 4)
plt.contourf(X1,Y1,var1,20,cmap='BuGn')
plt.colorbar()
plt.contour(X1,Y1,var1,20,colors='black',linewidths=0.5)
plt.savefig('../plots/heat_exchange_coefficient_'+expid+'.png',dpi=600)
plt.show()

plt.xlabel('Hour')
plt.ylabel('Level number')
plt.ylim(nlev-1,1,-1)
plt.xlim(0,nstep-1)
plt.xticks(np.arange(0,nstep,12))
plt.yticks(np.arange(0,nlev-1,5))
xvar=np.reshape(km,(nstep,nlev))
var1=xvar.transpose()
plt.title('Momentum exchange coefficient (m$^2$/s)')
figure = plt.gcf()
figure.set_size_inches(7, 4)
plt.contourf(X1,Y1,var1,20,cmap='BuGn')
plt.colorbar()
plt.contour(X1,Y1,var1,20,colors='black',linewidths=0.5)
plt.savefig('../plots/momentum_exchange_coefficient_'+expid+'.png',dpi=600)
plt.show()

