import numpy as np
import matplotlib.pyplot as plt
ug,vg=np.loadtxt("../data_in/Wangara_day33-34_UG_VG_L80.dat",unpack='True')
xvg=np.reshape(vg,(49,81))
xug=np.reshape(ug,(49,81))
ug1=xug.transpose()
vg1=xvg.transpose()
x1 = np.arange(0,49)
y1 = np.arange(0,81)
X1, Y1 = np.meshgrid(x1,y1)
plt.title('Zonal geostrophic wind (m/s) - WANGARA')
plt.xlabel('Hours')
plt.ylabel('Level number')
plt.ylim(80,0,-1)
plt.xlim(0,48)
plt.xticks(np.arange(0,49,3))
plt.yticks(np.arange(0,81,10))
plt.contourf(X1,Y1,ug1,20,cmap='Spectral')
plt.colorbar()
plt.contour(X1,Y1,ug1,20,colors='black',linestyles='solid',linewidths=0.5)
figure = plt.gcf()
figure.set_size_inches(7, 4)
plt.savefig('../plots/Ug_wangara.png',dpi=600)
plt.show()
plt.title('Meridional geostrophic wind (m/s) - WANGARA')
plt.xlabel('Hours')
plt.ylabel('Level number')
plt.ylim(80,0,-1)
plt.xlim(0,48)
plt.xticks(np.arange(0,49,3))
plt.yticks(np.arange(0,81,5))
plt.contourf(X1,Y1,vg1,20,cmap='Spectral')
plt.colorbar()
plt.contour(X1,Y1,vg1,20,colors='black',linestyles='solid',linewidths=0.5)
figure = plt.gcf()
figure.set_size_inches(7, 4)
plt.savefig('../plots/Vg_wangara.png',dpi=600)
plt.show()

